spring:
  datasource:
    username: root
    password: roottoor
    url: jdbc:mysql://47.98.137.243:3306/gulimall_pms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.137.243:8848
  redis:
    host: 47.98.137.243
    port: 6379
  #    alicloud:
#      access-key: LTAI5tSAk4xmqeMXc6f3xd
#      secret-key: HPG92M7qM1nFWcixV6GZpytcV8e8
#      oss:
#        endpoint: oss-cn-chengdu.aliyuncs.com
  application:
    name: gulimall-product
  cache:
    type: redis
    redis:
      time-to-live: 60000
      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true # 是否缓存空值，防止缓存穿透
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # classpath* 表示不止扫描本项目的类路径，还扫描引用的jar包的类路径
  global-config:
    db-config:
      id-type: auto   # 主键生成策略，自增   也可以在entity类的 @TableId配置
      logic-delete-value: 1 # 逻辑已删除（默认为1）
      logic-not-delete-value: 0 #逻辑未删除（默认为0）
server:
  port: 10001
logging:
  level:
    com.lvboaa.gulimall: debug