apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gulimall-cart
  name: gulimall-cart
  namespace: gulimall
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gulimall-cart
  template:
    metadata:
      labels:
        name: gulimall-cart
    spec:
      containers:
        - name: gulimall-cart
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gulimall-cart
  name: gulimall-cart
  namespace: gulimall
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080          # pod端口
      targetPort: 8080    # 容器端口
      nodePort: 31002     # 对外访问的端口
  selector:
    name: gulimall-cart
  type: NodePort
  sessionAffinity: None

