spring:
  datasource:
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    url: @spring.datasource.url@/gulimall_sms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    sentinel:
      transport:
        port: 8722  # 微服务和控制台传输数据的端口，只要不被占用即可
        dashboard: @sentinel-dashboard-addr@
  application:
    name: gulimall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # classpath* 表示不止扫描本项目的类路径，还扫描引用的jar包的类路径
  global-config:
    db-config:
      id-type: auto   # 主键生成策略，自增   也可以在entity类的 @TableId配置
server:
  port: 7000
logging:
  level:
    com.lvboaa.gulimall: debug

feign:
  sentinel:
    enabled: true