spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
  application:
    name: gulimall-auth-server
  alicloud:
    sms:
      accessKeyId: asdadsadsa
      secret: sadasdadad
      signName: 橘子科技
      templateCode: SMS_224900336
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
  session:
    store-type: redis

server:
  port: 20001
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.lvboaa.gulimall: debug
