spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    sentinel:
      transport:
        port: 8720  # 微服务和控制台传输数据的端口，只要不被占用即可
        dashboard: @sentinel-dashboard-addr@
  application:
    name: gulimall-auth-server
  alicloud:
    sms:
      accessKeyId: asdadsadsa
      secret: sadasdadad
      signName: 橘子科技
      templateCode: SMS_224900336
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
  session:
    store-type: redis

server:
  port: 20001
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.lvboaa.gulimall: debug

feign:
  sentinel:
    enabled: true
