server:
  port: @seckill.port@
spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    sentinel:
      transport:
        port: 8719  # 微服务和控制台传输数据的端口，只要不被占用即可
        dashboard: @sentinel-dashboard-addr@
  application:
    name: gulimall-seckill
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
  session:
    store-type: redis
  thymeleaf:
    cache: false
  rabbitmq:
    virtual-host: /
    host: @spring.rabbit.host@
    username: admin
    password: admin
    port: 5672
  zipkin:
    base-url: @zipkin.baseUrl@  # zipkin服务器地址
    discovery-client-enabled: false # 关闭服务发现，否则springcloud会把zipkin的url当成服务器名
    sender:
      type: web # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认是0.1，也就是10%的采样请求数据

#    publisher-confirms: true  # 开启发送端确认
#    publisher-returns: true   # 开启发送端消息抵达队列的确认
#    template:
#      mandatory: true     # 只要抵达队列，以异步发送优先回调return确认
#    listener:
#      simple:
#        acknowledge-mode: manual  # 手动确认ack消息
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.lvboaa.gulimall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

