server:
  port: 25000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
  application:
    name: gulimall-seckill
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
  session:
    store-type: redis
  thymeleaf:
    cache: false
  rabbitmq:
    virtual-host: /
    host: @spring.rabbit.host@
    username: admin
    password: admin
    port: 5672

#    publisher-confirms: true  # 开启发送端确认
#    publisher-returns: true   # 开启发送端消息抵达队列的确认
#    template:
#      mandatory: true     # 只要抵达队列，以异步发送优先回调return确认
#    listener:
#      simple:
#        acknowledge-mode: manual  # 手动确认ack消息

logging:
  level:
    com.lvboaa.gulimall: debug

