spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    sentinel:
      transport:
        port: 8726  # 微服务和控制台传输数据的端口，只要不被占用即可
        dashboard: @sentinel-dashboard-addr@
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
  session:
    store-type: redis
server:
  port: 4000
  servlet:
    session:
      timeout: 30m
feign:
  sentinel:
    enabled: true
es:
  server:
    url: 127.0.0.1
   #port: 9200
    scheme: http
logging:
  level:
    com.lvboaa.gulimall: debug