spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    sentinel:
      transport:
        port: 8726  # 微服务和控制台传输数据的端口，只要不被占用即可
        dashboard: @sentinel-dashboard-addr@
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
  session:
    store-type: redis
  zipkin:
    base-url: http://192.168.131.131:9411/  # zipkin服务器地址
    discovery-client-enabled: false # 关闭服务发现，否则springcloud会把zipkin的url当成服务器名
    sender:
      type: web # 设置使用http的方式传输数据
    sleuth:
      sampler:
        probability: 1  # 设置抽样采集率为100%，默认是0.1，也就是10%的采样请求数据

server:
  port: 4000
  servlet:
    session:
      timeout: 30m
feign:
  sentinel:
    enabled: true
es:
  server:
    url: 127.0.0.1
   #port: 9200
    scheme: http
logging:
  level:
    com.lvboaa.gulimall: debug