spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.137.243:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 47.98.137.243
    port: 6379
  session:
    store-type: redis
server:
  port: 4000
  servlet:
    session:
      timeout: 30m
es:
  server:
    url: 127.0.0.1
   #port: 9200
    scheme: http
logging:
  level:
    com.lvboaa.gulimall: debug