spring:
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu        # 断言 Query=k,v 就是 url路径带参数 ?k=v
        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://gulimall-product    # 默认按前后顺序优先匹配，细粒度的匹配规则放在上面
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast      # loadbalance 将请求路由给renren-fast 路由
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        - id: search_gulimall_host_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        - id: auth_gulimall_host_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com
        - id: cart_gulimall_host_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        - id: order_gulimall_host_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

#      globalcors:
#        cors-configurations:
#           允许https://docs.spring.io路径下所有GET请求跨域  配置跨域 可以用*代表所有请求和所有路径
#          '[/**]':
#            allowedOrigins: "https://docs.spring.io"
#            allowedMethods:
#              - GET

  application:
    name: gulimall-gateway
server:
  port: 88
logging:
  level:
    com.lvboaa.gulimall: debug