spring:
  datasource:
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    url: @spring.datasource.url@/gulimall_wms?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: @nacos-server-addr@
    sentinel:
      transport:
        port: 8727  # 微服务和控制台传输数据的端口，只要不被占用即可
        dashboard: @sentinel-dashboard-addr@
#    alibaba:
#      seata:
#        tx-service-group: gulimall-ware-fescar-server-group
  application:
    name: gulimall-ware
  rabbitmq:
    host: @spring.rabbit.host@
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml  # classpath* 表示不止扫描本项目的类路径，还扫描引用的jar包的类路径
  global-config:
    db-config:
      id-type: auto   # 主键生成策略，自增   也可以在entity类的 @TableId配置
server:
  port: 11000
logging:
  level:
    com.lvboaa.gulimall: debug
feign:
  sentinel:
    enabled: true